{
    'name': 'TeknoParts Inventory – Spare-part HP',
    'version': '17.0.1.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Gudang spare-part handphone, QC, recondition, opname',
    'description': """
        Long description diisi nanti
    """,
    'author': 'YourName',
    'website': 'https://www.faqihazh.my.id',
    'depends': ['base', 'product', 'stock', 'purchase', 'sale', 'report_xlsx'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/part_rule.xml',
        'security/picking_rule.xml',
        'data/sequence.xml',
        'wizard/qc_check_wizard.xml',
        'wizard/stock_opname_wizard.xml',
        'wizard/advanced_print_wizard.xml',
        'views/category_views.xml',
        'views/part_views.xml',
        'views/qc_check_views.xml',
        'views/inherit_existing.xml',
        'views/report_kartu_stock.xml',
        'views/report_qc_failure.xml',
        'views/advanced_pdf_templates.xml',
        'views/advanced_report_actions.xml',
        'views/report_action.xml',
        'views/stock_opname_menu.xml'
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}